"""Reviewed safe defaults; independent of runtime configuration files."""

DEFAULTS = {'version': '2.0.0',
 'migration': 'recalculate',
 'stats': {'hp': {'cap': 500000, 'weight': 0.05, 'group': 'defense'},
           'attack': {'cap': 60000, 'weight': 1.0, 'group': 'offense'},
           'magicAttack': {'cap': 60000, 'weight': 1.0, 'group': 'offense'},
           'physDef': {'cap': 30000, 'weight': 0.6, 'group': 'defense'},
           'magicDef': {'cap': 30000, 'weight': 0.6, 'group': 'defense'},
           'crit': {'cap': 40000, 'weight': 1.1, 'group': 'offense'},
           'dh': {'cap': 40000, 'weight': 1.3, 'group': 'offense'},
           'det': {'cap': 40000, 'weight': 1.2, 'group': 'offense'},
           'sks': {'cap': 50, 'weight': 0.5, 'group': 'offense'},
           'sps': {'cap': 70, 'weight': 1.0, 'group': 'sustain'},
           'regen': {'cap': 10000, 'weight': 0.3, 'group': 'sustain'},
           'lifesteal': {'cap': 50, 'weight': 0.5, 'group': 'sustain'},
           'dodge': {'cap': 30, 'weight': 0.5, 'group': 'defense'},
           'acc': {'cap': 20, 'weight': 0.4, 'group': 'offense'},
           'tenacity': {'cap': 50, 'weight': 0.5, 'group': 'sustain'},
           'mpRegen': {'cap': 1000, 'weight': 0.3, 'group': 'sustain'},
           'damageReduce': {'cap': 50, 'weight': 30, 'group': 'defense'},
           'penetration': {'cap': 100, 'weight': 5, 'group': 'offense'},
           'skillDamage': {'cap': 200, 'weight': 10, 'group': 'offense'},
           'cooldown': {'cap': 70, 'weight': 5, 'group': 'sustain'}},
 'normal': {'damage': 0.35,
            'taken': 0.3,
            'healing': 0.25,
            'resource': 0.2,
            'cooldown': 0.15,
            'window': 0.2,
            'reward': 0.4,
            'hit': 0.1,
            'hitFloor': 0.8},
 'regions': {'1': {'power': 0,
                   'quality': 0,
                   'attack': 0,
                   'defense': 0,
                   'prerequisite': 0,
                   'trial': False,
                   'recommendedPower': 100},
             '2': {'power': 400,
                   'quality': 0,
                   'attack': 16,
                   'defense': 8,
                   'prerequisite': 1,
                   'trial': True,
                   'recommendedPower': 900},
             '3': {'power': 900,
                   'quality': 0,
                   'attack': 36,
                   'defense': 18,
                   'prerequisite': 2,
                   'trial': True,
                   'recommendedPower': 1800},
             '4': {'power': 1400,
                   'quality': 0,
                   'attack': 56,
                   'defense': 28,
                   'prerequisite': 3,
                   'trial': True,
                   'recommendedPower': 2700},
             '5': {'power': 1900,
                   'quality': 0,
                   'attack': 76,
                   'defense': 38,
                   'prerequisite': 4,
                   'trial': True,
                   'recommendedPower': 3600},
             '6': {'power': 2400,
                   'quality': 1,
                   'attack': 96,
                   'defense': 48,
                   'prerequisite': 5,
                   'trial': True,
                   'recommendedPower': 4500},
             '7': {'power': 2900,
                   'quality': 1,
                   'attack': 116,
                   'defense': 58,
                   'prerequisite': 6,
                   'trial': True,
                   'recommendedPower': 5400},
             '8': {'power': 3400,
                   'quality': 1,
                   'attack': 136,
                   'defense': 68,
                   'prerequisite': 7,
                   'trial': True,
                   'recommendedPower': 6300},
             '9': {'power': 3900,
                   'quality': 1,
                   'attack': 156,
                   'defense': 78,
                   'prerequisite': 8,
                   'trial': True,
                   'recommendedPower': 7200},
             '10': {'power': 4400,
                    'quality': 2,
                    'attack': 176,
                    'defense': 88,
                    'prerequisite': 9,
                    'trial': True,
                    'recommendedPower': 8100},
             '11': {'power': 4900,
                    'quality': 2,
                    'attack': 196,
                    'defense': 98,
                    'prerequisite': 10,
                    'trial': True,
                    'recommendedPower': 9000},
             '12': {'power': 5200,
                    'quality': 2,
                    'attack': 208,
                    'defense': 104,
                    'prerequisite': 11,
                    'trial': True,
                    'recommendedPower': 9540},
             '13': {'power': 5400,
                    'quality': 2,
                    'attack': 216,
                    'defense': 108,
                    'prerequisite': 12,
                    'trial': True,
                    'recommendedPower': 9900},
             '14': {'power': 5600,
                    'quality': 2,
                    'attack': 224,
                    'defense': 112,
                    'prerequisite': 13,
                    'trial': True,
                    'recommendedPower': 10260},
             '15': {'power': 5700,
                    'quality': 2,
                    'attack': 228,
                    'defense': 114,
                    'prerequisite': 14,
                    'trial': True,
                    'recommendedPower': 10440},
             '16': {'power': 5800,
                    'quality': 2,
                    'attack': 232,
                    'defense': 116,
                    'prerequisite': 15,
                    'trial': True,
                    'recommendedPower': 10620},
             '17': {'power': 5900,
                    'quality': 2,
                    'attack': 236,
                    'defense': 118,
                    'prerequisite': 16,
                    'trial': True,
                    'recommendedPower': 10800},
             '18': {'power': 6200,
                    'quality': 3,
                    'attack': 248,
                    'defense': 124,
                    'prerequisite': 17,
                    'trial': True,
                    'recommendedPower': 11340},
             '19': {'power': 6400,
                    'quality': 3,
                    'attack': 256,
                    'defense': 128,
                    'prerequisite': 18,
                    'trial': True,
                    'recommendedPower': 11700},
             '20': {'power': 6600,
                    'quality': 3,
                    'attack': 264,
                    'defense': 132,
                    'prerequisite': 19,
                    'trial': True,
                    'recommendedPower': 12060},
             '21': {'power': 6700,
                    'quality': 3,
                    'attack': 268,
                    'defense': 134,
                    'prerequisite': 20,
                    'trial': True,
                    'recommendedPower': 12240},
             '22': {'power': 6800,
                    'quality': 3,
                    'attack': 272,
                    'defense': 136,
                    'prerequisite': 21,
                    'trial': True,
                    'recommendedPower': 12420},
             '23': {'power': 6900,
                    'quality': 3,
                    'attack': 276,
                    'defense': 138,
                    'prerequisite': 22,
                    'trial': True,
                    'recommendedPower': 12600},
             '24': {'power': 7200,
                    'quality': 3,
                    'attack': 288,
                    'defense': 144,
                    'prerequisite': 23,
                    'trial': True,
                    'recommendedPower': 13140},
             '25': {'power': 7400,
                    'quality': 3,
                    'attack': 296,
                    'defense': 148,
                    'prerequisite': 24,
                    'trial': True,
                    'recommendedPower': 13500},
             '26': {'power': 7600,
                    'quality': 3,
                    'attack': 304,
                    'defense': 152,
                    'prerequisite': 25,
                    'trial': True,
                    'recommendedPower': 13860},
             '27': {'power': 7700,
                    'quality': 3,
                    'attack': 308,
                    'defense': 154,
                    'prerequisite': 26,
                    'trial': True,
                    'recommendedPower': 14040},
             '28': {'power': 7800,
                    'quality': 3,
                    'attack': 312,
                    'defense': 156,
                    'prerequisite': 27,
                    'trial': True,
                    'recommendedPower': 14220},
             '29': {'power': 7900,
                    'quality': 3,
                    'attack': 316,
                    'defense': 158,
                    'prerequisite': 28,
                    'trial': True,
                    'recommendedPower': 14400},
             '30': {'power': 8200,
                    'quality': 4,
                    'attack': 328,
                    'defense': 164,
                    'prerequisite': 29,
                    'trial': True,
                    'recommendedPower': 14940},
             '31': {'power': 8400,
                    'quality': 4,
                    'attack': 336,
                    'defense': 168,
                    'prerequisite': 30,
                    'trial': True,
                    'recommendedPower': 15300},
             '32': {'power': 8600,
                    'quality': 4,
                    'attack': 344,
                    'defense': 172,
                    'prerequisite': 31,
                    'trial': True,
                    'recommendedPower': 15660},
             '33': {'power': 8700,
                    'quality': 4,
                    'attack': 348,
                    'defense': 174,
                    'prerequisite': 32,
                    'trial': True,
                    'recommendedPower': 15840},
             '34': {'power': 8800,
                    'quality': 4,
                    'attack': 352,
                    'defense': 176,
                    'prerequisite': 33,
                    'trial': True,
                    'recommendedPower': 16020},
             '35': {'power': 8900,
                    'quality': 4,
                    'attack': 356,
                    'defense': 178,
                    'prerequisite': 34,
                    'trial': True,
                    'recommendedPower': 16200},
             '36': {'power': 9200,
                    'quality': 4,
                    'attack': 368,
                    'defense': 184,
                    'prerequisite': 35,
                    'trial': True,
                    'recommendedPower': 16740},
             '37': {'power': 9400,
                    'quality': 4,
                    'attack': 376,
                    'defense': 188,
                    'prerequisite': 36,
                    'trial': True,
                    'recommendedPower': 17100},
             '38': {'power': 9600,
                    'quality': 4,
                    'attack': 384,
                    'defense': 192,
                    'prerequisite': 37,
                    'trial': True,
                    'recommendedPower': 17460},
             '39': {'power': 9700,
                    'quality': 4,
                    'attack': 388,
                    'defense': 194,
                    'prerequisite': 38,
                    'trial': True,
                    'recommendedPower': 17640},
             '40': {'power': 9800,
                    'quality': 4,
                    'attack': 392,
                    'defense': 196,
                    'prerequisite': 39,
                    'trial': True,
                    'recommendedPower': 17820}},
 'raids': {'raid_1': {'power': 10000,
                      'attack': 240,
                      'defense': 80,
                      'maxFightSeconds': 600,
                      'minSurvivalSeconds': 12,
                      'requiredLevel': 20,
                      'requiresAllSlots': True,
                      'minEquipRarity': 'mythic',
                      'topRarity': None,
                      'topRarityRatio': 0.0,
                      'minAncientTermsPerItem': 2,
                      'durationTolerance': 0.5,
                      'clockToleranceMs': 2000},
           'raid_2': {'power': 25000,
                      'attack': 480,
                      'defense': 160,
                      'maxFightSeconds': 600,
                      'minSurvivalSeconds': 12,
                      'requiredLevel': 40,
                      'requiresAllSlots': True,
                      'minEquipRarity': 'mythic',
                      'topRarity': None,
                      'topRarityRatio': 0.0,
                      'minAncientTermsPerItem': 2,
                      'durationTolerance': 0.5,
                      'clockToleranceMs': 2000},
           'raid_3': {'power': 42000,
                      'attack': 720,
                      'defense': 240,
                      'maxFightSeconds': 600,
                      'minSurvivalSeconds': 12,
                      'requiredLevel': 60,
                      'requiresAllSlots': True,
                      'minEquipRarity': 'mythic',
                      'topRarity': None,
                      'topRarityRatio': 0.0,
                      'minAncientTermsPerItem': 2,
                      'durationTolerance': 0.5,
                      'clockToleranceMs': 2000},
           'raid_4': {'power': 52000,
                      'attack': 960,
                      'defense': 320,
                      'maxFightSeconds': 600,
                      'minSurvivalSeconds': 12,
                      'requiredLevel': 80,
                      'requiresAllSlots': True,
                      'minEquipRarity': 'mythic',
                      'topRarity': None,
                      'topRarityRatio': 0.0,
                      'minAncientTermsPerItem': 2,
                      'durationTolerance': 0.5,
                      'clockToleranceMs': 2000},
           'raid_h1': {'power': 60000,
                       'attack': 1200,
                       'defense': 400,
                       'maxFightSeconds': 600,
                       'minSurvivalSeconds': 12,
                       'requiredLevel': 100,
                       'requiresAllSlots': True,
                       'minEquipRarity': 'mythic',
                       'topRarity': None,
                       'topRarityRatio': 0.0,
                       'minAncientTermsPerItem': 2,
                       'durationTolerance': 0.5,
                       'clockToleranceMs': 2000},
           'raid_h2': {'power': 62000,
                       'attack': 1200,
                       'defense': 400,
                       'maxFightSeconds': 600,
                       'minSurvivalSeconds': 12,
                       'requiredLevel': 100,
                       'requiresAllSlots': True,
                       'minEquipRarity': 'mythic',
                       'topRarity': None,
                       'topRarityRatio': 0.0,
                       'minAncientTermsPerItem': 3,
                       'durationTolerance': 0.5,
                       'clockToleranceMs': 2000}},
 'telemetry': {'days': 30,
               'targetLow': 0.45,
               'targetHigh': 0.55,
               'consecutiveWindows': 3,
               'minimumPlayers': 30},
 'trial': {'rounds': 3, 'windowSeconds': 8, 'minResponseSeconds': 0.15}}
