"""initial schema

Revision ID: 451f3379f026
Revises: 
Create Date: 2026-09-20 12:00:45.459763

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '451f3379f026'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('gold', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('auto_sell_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rarities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_sell_settings_user_id'), 'auto_sell_settings', ['user_id'], unique=True)
    op.create_table('battle_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_report_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kill_credit', sa.Float(), nullable=False),
    sa.Column('total_kills', sa.BigInteger(), nullable=False),
    sa.Column('total_gold', sa.BigInteger(), nullable=False),
    sa.Column('total_exp', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_sessions_active'), 'battle_sessions', ['active'], unique=False)
    op.create_index(op.f('ix_battle_sessions_user_id'), 'battle_sessions', ['user_id'], unique=False)
    op.create_table('chest_pity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chest_type', sa.String(length=32), nullable=False),
    sa.Column('since_rare', sa.Integer(), nullable=False),
    sa.Column('since_epic', sa.Integer(), nullable=False),
    sa.Column('since_legendary', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chest_type', name='uq_pity_user_chest')
    )
    op.create_index(op.f('ix_chest_pity_user_id'), 'chest_pity', ['user_id'], unique=False)
    op.create_table('codex_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.String(length=48), nullable=False),
    sa.Column('unlocked_rarities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('first_unlock_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'base_id', name='uq_codex_equip')
    )
    op.create_index(op.f('ix_codex_equipment_base_id'), 'codex_equipment', ['base_id'], unique=False)
    op.create_index(op.f('ix_codex_equipment_user_id'), 'codex_equipment', ['user_id'], unique=False)
    op.create_table('codex_monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.String(length=64), nullable=False),
    sa.Column('kill_count', sa.Integer(), nullable=False),
    sa.Column('first_defeat_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'monster_id', name='uq_codex_monster')
    )
    op.create_index(op.f('ix_codex_monsters_monster_id'), 'codex_monsters', ['monster_id'], unique=False)
    op.create_index(op.f('ix_codex_monsters_user_id'), 'codex_monsters', ['user_id'], unique=False)
    op.create_table('codex_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.String(length=48), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'term_id', 'quality', name='uq_codex_term')
    )
    op.create_index(op.f('ix_codex_terms_term_id'), 'codex_terms', ['term_id'], unique=False)
    op.create_index(op.f('ix_codex_terms_user_id'), 'codex_terms', ['user_id'], unique=False)
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('exp', sa.BigInteger(), nullable=False),
    sa.Column('talent', sa.String(length=16), nullable=False),
    sa.Column('attr_bias', sa.String(length=16), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('intellect', sa.Integer(), nullable=False),
    sa.Column('current_region_id', sa.Integer(), nullable=True),
    sa.Column('region_kill_count', sa.Integer(), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_user_id'), 'heroes', ['user_id'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('level_req', sa.Integer(), nullable=False),
    sa.Column('base_attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sub_attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('refine_count', sa.Integer(), nullable=False),
    sa.Column('enchant_count', sa.Integer(), nullable=False),
    sa.Column('equipped_slot', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_base_id'), 'items', ['base_id'], unique=False)
    op.create_index(op.f('ix_items_equipped_slot'), 'items', ['equipped_slot'], unique=False)
    op.create_index(op.f('ix_items_rarity'), 'items', ['rarity'], unique=False)
    op.create_index('ix_items_user_base', 'items', ['user_id', 'base_id'], unique=False)
    op.create_index(op.f('ix_items_user_id'), 'items', ['user_id'], unique=False)
    op.create_index('ix_items_user_slot', 'items', ['user_id', 'equipped_slot'], unique=False)
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(length=16), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('secondary', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'board', name='uq_ranking_user_board')
    )
    op.create_index(op.f('ix_rankings_user_id'), 'rankings', ['user_id'], unique=False)
    # 表达式索引仅在 PostgreSQL 上创建（SQLite 不支持）
    if op.get_bind().dialect.name == 'postgresql':
        op.create_index(
            'ix_rankings_board_value', 'rankings', ['board', sa.text('value DESC')], unique=False
        )
    op.create_table('region_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('cleared', sa.Boolean(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('best_clear_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'region_id', name='uq_progress_user_region')
    )
    op.create_index(op.f('ix_region_progress_user_id'), 'region_progress', ['user_id'], unique=False)
    op.create_table('tavern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('candidate', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('free_refresh_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tavern_user_id'), 'tavern', ['user_id'], unique=True)
    op.create_table('tutorial_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('rewarded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutorial_progress_user_id'), 'tutorial_progress', ['user_id'], unique=True)
    op.create_table('hero_skill_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=16), nullable=False),
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.Column('cast_count', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero_id', 'skill_id', name='uq_hero_skill')
    )
    op.create_index(op.f('ix_hero_skill_stats_hero_id'), 'hero_skill_stats', ['hero_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hero_skill_stats_hero_id'), table_name='hero_skill_stats')
    op.drop_table('hero_skill_stats')
    op.drop_index(op.f('ix_tutorial_progress_user_id'), table_name='tutorial_progress')
    op.drop_table('tutorial_progress')
    op.drop_index(op.f('ix_tavern_user_id'), table_name='tavern')
    op.drop_table('tavern')
    op.drop_index(op.f('ix_region_progress_user_id'), table_name='region_progress')
    op.drop_table('region_progress')
    if op.get_bind().dialect.name == 'postgresql':
        op.drop_index('ix_rankings_board_value', table_name='rankings')
    op.drop_index(op.f('ix_rankings_user_id'), table_name='rankings')
    op.drop_table('rankings')
    op.drop_index('ix_items_user_slot', table_name='items')
    op.drop_index(op.f('ix_items_user_id'), table_name='items')
    op.drop_index('ix_items_user_base', table_name='items')
    op.drop_index(op.f('ix_items_rarity'), table_name='items')
    op.drop_index(op.f('ix_items_equipped_slot'), table_name='items')
    op.drop_index(op.f('ix_items_base_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_heroes_user_id'), table_name='heroes')
    op.drop_table('heroes')
    op.drop_index(op.f('ix_codex_terms_user_id'), table_name='codex_terms')
    op.drop_index(op.f('ix_codex_terms_term_id'), table_name='codex_terms')
    op.drop_table('codex_terms')
    op.drop_index(op.f('ix_codex_monsters_user_id'), table_name='codex_monsters')
    op.drop_index(op.f('ix_codex_monsters_monster_id'), table_name='codex_monsters')
    op.drop_table('codex_monsters')
    op.drop_index(op.f('ix_codex_equipment_user_id'), table_name='codex_equipment')
    op.drop_index(op.f('ix_codex_equipment_base_id'), table_name='codex_equipment')
    op.drop_table('codex_equipment')
    op.drop_index(op.f('ix_chest_pity_user_id'), table_name='chest_pity')
    op.drop_table('chest_pity')
    op.drop_index(op.f('ix_battle_sessions_user_id'), table_name='battle_sessions')
    op.drop_index(op.f('ix_battle_sessions_active'), table_name='battle_sessions')
    op.drop_table('battle_sessions')
    op.drop_index(op.f('ix_auto_sell_settings_user_id'), table_name='auto_sell_settings')
    op.drop_table('auto_sell_settings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
